apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-estate
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: my-app
        image: nginx:1.16.0
        ports:
        - containerPort: 80
    