resources:
  - ../../base
namePrefix: dev-
patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: my-app
      namespace: default
configMapGenerator:
  - files:
      - config.yaml
    name: config
