// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID        int32       `json:"id"`
	UserID    pgtype.Int4 `json:"user_id"`
	Title     string      `json:"title"`
	Completed bool        `json:"completed"`
}

type User struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
