apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api
  name: api
spec:
  ports:
  - name: "1323"
    port: 1323
    protocol: TCP
    targetPort: 1323
  selector:
    app: api
  type: NodePort
status:
  loadBalancer: {}
