apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db-svc
  name: db-svc
spec:
  ports:
    - name: db-port
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: db
  type: NodePort
