apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-user
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: my-app-user
        image: nginx:1.16.0
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config  
      volumes:
        - name: config-volume
          configMap:
            name: config